package tools;
/**
 * COMPILATION OF ALL MY CUSTOM USER DATA.
 */
public enum AUserData {
	//TODO DO ALL OF THEm
	//PLAYER DATA
	CORE,
	BOTTOM_EXT,LEFT_EXT,RIGHT_EXT,TOP_EXT, //FIXTURE EXTENSIONS
	
	//ZONES
 YOUWINZONE, DEATH_ZONE, 
 
 //BLOCKS
 PLATFORM, ROTATING_BLOCK
	
	
	
}
